## This file was auto-generated by CloudCoreo CLI
## This file was automatically generated using the CloudCoreo CLI
##
## This config.rb file exists to create and maintain services not related to compute.
## for example, a VPC might be maintained using:
##
## coreo_aws_vpc_vpc "my-vpc" do
##   action :sustain
##   cidr "12.0.0.0/16"
##   internet_gateway true
## end
##

coreo_uni_util_jsrunner "ip-splitter" do
  action :run
  data_type "text"
  json_input '{}'
  function <<-EOH
var out = "COMPOSITE::coreo_aws_ec2_autoscaling.${CLUSTER_NAME}.private_ip_addresses".replace(/,/g, "\\",\\"");
callback(out);
  EOH
end

coreo_aws_route53_record "${CLUSTER_NAME}-private" do
  action :sustain
  type "A"
  zone "${DNS_ZONE}"
  values ['COMPOSITE::coreo_uni_util_jsrunner.ip-splitter.return']
end
